version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short_url_api
    env_file:
      - .env
    ports:
      - 3000:${API_PORT}
    volumes:
      - .:/api
    depends_on:
      - db

  db:
    image: postgres:16.0
    container_name: short_url_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
